import { IonDatetime } from "@ionic/angular";
import { NotebookEntry } from "./notebook-entry";

export class EnviroPost {

   salutation: string = '';
   first_name: string = '';
   last_name: string = '';
   address: string = '';
   town: string = '';
   county: string = 'United Kingdom';
   post_code: string = '';
   phone: string = '';
   date_of_birth: string = '';
   ethnicity_id: number = 1;
   gender: string = '';
   is_bwc_active: string = '';
   proof_of_address: string = '';
   proof_of_id: string = '';
   ref_no: string = '';
   site_id: number = 1;
   zone_id: number = 1;
   officer_id: number = 1;
   offence_id: number = 1;
   offence_type_id: number = 0;
   language: string = '';
   admin_id: number = 1;
   offender_id: number = 1;
   prefix_id: number = 1;
   location_id: number = 1;
   action_id: number = 1;
   caution: string = '';
   second_caution: string = '';
   offender_reply: string = '';
   description: string = '';
   description_waste: string = '';
   offence_location: string = '';
   land_type_id: number = 1;
   town_area: string = '';
   poi_prefix_id: number = 1;
   poi: string = '';
   visibility_id: number = 1;
   weather_id: number = 1;
   offence_datetime: string = '';
   issue_datetime: string = '';
   enviro_issued_onspot: string = '';
   is_id_verified: string = '';
   is_address_verified: string = '';
   lat: string = '';
   lng: string = '';
   is_witness_available: string = '';
   witness_name: string = '';
   witness_phone: string = '';
   witness_address: string = '';
   witness_statement: string = '';
   officer_statement: string = '';
   signature: any;
   offence_images: any[] = [];
   notebook_entries!: NotebookEntry;
}